2025-02-23 17:29:31,657 - app.routers.instruments - INFO - Начат поиск и добавление средства измерений для узла с ID=4. Параметры поиска: search=УДВН, mit_number=14557-15, mi_number=3261, year=2024
2025-02-23 17:29:31,657 - app.routers.instruments - INFO - Выполняется GET-запрос к API 'АРШИН' с параметрами: {'search': '*УДВН*', 'mit_number': '14557-15', 'mi_number': '3261', 'year': 2024}
2025-02-23 17:29:39,058 - app.routers.instruments - INFO - Создание нового средства измерений с mit_number=14557-15 и mi_number=3261
2025-02-23 17:30:43,427 - app.routers.instruments - INFO - Начат поиск и добавление средства измерений для узла с ID=4. Параметры поиска: search=УДВН, mit_number=14557-15, mi_number=3261, year=2024
2025-02-23 17:30:43,427 - app.routers.instruments - INFO - Выполняется GET-запрос к API 'АРШИН' с параметрами: {'search': '*УДВН*', 'mit_number': '14557-15', 'mi_number': '3261', 'year': 2024}
2025-02-23 17:30:51,553 - app.routers.instruments - WARNING - Попытка добавить уже существующий прибор с mit_number=14557-15 и mi_number=3261
2025-02-23 17:30:51,553 - app.routers.instruments - ERROR - Произошла ошибка при выполнении запроса к API 'АРШИН': 409: Прибор уже существует в базе данных.
2025-02-25 13:26:44,036 - app.routers.instruments - INFO - Начат поиск и добавление средства измерений для узла с ID=13. Параметры поиска: search=АБАК, mit_number=, mi_number=1344, year=2024
2025-02-25 13:26:44,036 - app.routers.instruments - INFO - Выполняется GET-запрос к API 'АРШИН' с параметрами: {'search': '*АБАК*', 'mi_number': '1344', 'year': 2024}
2025-02-25 13:26:51,904 - app.routers.instruments - INFO - Средства измерений не найдены.
2025-02-25 13:28:18,217 - app.routers.instruments - INFO - Начат поиск и добавление средства измерений для узла с ID=13. Параметры поиска: search=УДВН, mit_number=14557-15, mi_number=3262, year=2025
2025-02-25 13:28:18,217 - app.routers.instruments - INFO - Выполняется GET-запрос к API 'АРШИН' с параметрами: {'search': '*УДВН*', 'mit_number': '14557-15', 'mi_number': '3262', 'year': 2025}
2025-02-25 13:28:21,107 - app.routers.instruments - INFO - Создание нового средства измерений с mit_number=14557-15 и mi_number=3262
2025-02-25 13:58:33,768 - app.routers.instruments - INFO - Начат поиск и добавление средства измерений для узла с ID=72. Параметры поиска: search=, mit_number=52866-13, mi_number=1844, year=2024
2025-02-25 13:58:33,768 - app.routers.instruments - INFO - Выполняется GET-запрос к API 'АРШИН' с параметрами: {'mit_number': '52866-13', 'mi_number': '1844', 'year': 2024}
2025-02-25 13:58:35,370 - app.routers.instruments - INFO - Создание нового средства измерений с mit_number=52866-13 и mi_number=1844
2025-02-25 13:59:57,450 - app.routers.instruments - INFO - Начат поиск и добавление средства измерений для узла с ID=73. Параметры поиска: search=, mit_number=52866-13, mi_number=1844, year=2024
2025-02-25 13:59:57,450 - app.routers.instruments - INFO - Выполняется GET-запрос к API 'АРШИН' с параметрами: {'mit_number': '52866-13', 'mi_number': '1844', 'year': 2024}
2025-02-25 13:59:59,123 - app.routers.instruments - INFO - Создание нового средства измерений с mit_number=52866-13 и mi_number=1844
2025-02-25 16:08:06,955 - app.routers.instruments - INFO - Начат поиск и добавление средства измерений для узла с ID=74. Параметры поиска: search=, mit_number=14557-15, mi_number=3262, year=2025
2025-02-25 16:08:06,955 - app.routers.instruments - INFO - Выполняется GET-запрос к API 'АРШИН' с параметрами: {'mit_number': '14557-15', 'mi_number': '3262', 'year': 2025}
2025-02-25 16:08:08,841 - app.routers.instruments - INFO - Создание нового средства измерений с mit_number=14557-15 и mi_number=3262
2025-02-25 16:19:19,879 - app.routers.instruments - INFO - Начат поиск и добавление средства измерений для узла с ID=74. Параметры поиска: search=УДВН, mit_number= 	14557-15, mi_number=3261, year=2025
2025-02-25 16:19:19,879 - app.routers.instruments - INFO - Выполняется GET-запрос к API 'АРШИН' с параметрами: {'search': '*УДВН*', 'mit_number': ' \t14557-15', 'mi_number': '3261', 'year': 2025}
2025-02-25 16:19:22,470 - app.routers.instruments - INFO - Средства измерений не найдены.
2025-02-25 16:19:43,112 - app.routers.instruments - INFO - Начат поиск и добавление средства измерений для узла с ID=74. Параметры поиска: search=, mit_number=14557-15, mi_number=3262, year=2024
2025-02-25 16:19:43,112 - app.routers.instruments - INFO - Выполняется GET-запрос к API 'АРШИН' с параметрами: {'mit_number': '14557-15', 'mi_number': '3262', 'year': 2024}
2025-02-25 16:19:44,823 - app.routers.instruments - INFO - Средства измерений не найдены.
2025-02-25 16:21:52,993 - app.routers.instruments - INFO - Начат поиск и добавление средства измерений для узла с ID=74. Параметры поиска: search=, mit_number=14557-15, mi_number=3261, year=2024
2025-02-25 16:21:52,993 - app.routers.instruments - INFO - Выполняется GET-запрос к API 'АРШИН' с параметрами: {'mit_number': '14557-15', 'mi_number': '3261', 'year': 2024}
2025-02-25 16:21:54,751 - app.routers.instruments - INFO - Создание нового средства измерений с mit_number=14557-15 и mi_number=3261
2025-02-26 22:06:32,770 - app.routers.instruments - INFO - Начат поиск и добавление средства измерений для узла с ID=74. Параметры поиска: search=, mit_number=14557-15, mi_number=3252, year=2024
2025-02-26 22:06:32,771 - app.routers.instruments - INFO - Выполняется GET-запрос к API 'АРШИН' с параметрами: {'mit_number': '14557-15', 'mi_number': '3252', 'year': 2024}
2025-02-26 22:06:45,825 - app.routers.instruments - INFO - Начат поиск и добавление средства измерений для узла с ID=74. Параметры поиска: search=, mit_number=14557-15, mi_number=3252, year=2024
2025-02-26 22:06:45,826 - app.routers.instruments - INFO - Выполняется GET-запрос к API 'АРШИН' с параметрами: {'mit_number': '14557-15', 'mi_number': '3252', 'year': 2024}
2025-02-26 22:06:48,834 - app.routers.instruments - INFO - Начат поиск и добавление средства измерений для узла с ID=74. Параметры поиска: search=, mit_number=14557-15, mi_number=3252, year=2025
2025-02-26 22:06:48,834 - app.routers.instruments - INFO - Выполняется GET-запрос к API 'АРШИН' с параметрами: {'mit_number': '14557-15', 'mi_number': '3252', 'year': 2025}
2025-02-26 22:07:19,425 - app.routers.instruments - INFO - Начат поиск и добавление средства измерений для узла с ID=74. Параметры поиска: search=, mit_number=14557-15, mi_number=3252, year=2024
2025-02-26 22:07:19,425 - app.routers.instruments - INFO - Выполняется GET-запрос к API 'АРШИН' с параметрами: {'mit_number': '14557-15', 'mi_number': '3252', 'year': 2024}
2025-02-26 22:07:56,984 - app.routers.instruments - INFO - Начат поиск и добавление средства измерений для узла с ID=74. Параметры поиска: search=УДВН, mit_number=14557-15, mi_number=3252, year=2024
2025-02-26 22:07:56,985 - app.routers.instruments - INFO - Выполняется GET-запрос к API 'АРШИН' с параметрами: {'search': '*УДВН*', 'mit_number': '14557-15', 'mi_number': '3252', 'year': 2024}
2025-02-26 22:08:03,249 - app.routers.instruments - INFO - Начат поиск и добавление средства измерений для узла с ID=74. Параметры поиска: search=УДВН, mit_number=, mi_number=3252, year=2024
2025-02-26 22:08:03,249 - app.routers.instruments - INFO - Выполняется GET-запрос к API 'АРШИН' с параметрами: {'search': '*УДВН*', 'mi_number': '3252', 'year': 2024}
2025-02-26 22:08:42,566 - app.routers.instruments - INFO - Начат поиск и добавление средства измерений для узла с ID=74. Параметры поиска: search=УДВН, mit_number=, mi_number=3252, year=2024
2025-02-26 22:08:42,566 - app.routers.instruments - INFO - Выполняется GET-запрос к API 'АРШИН' с параметрами: {'search': '*УДВН*', 'mi_number': '3252', 'year': 2024}
2025-02-26 22:08:48,218 - app.routers.instruments - ERROR - Произошла ошибка при выполнении запроса к API 'АРШИН': HTTPSConnectionPool(host='fgis.gost.ru', port=443): Max retries exceeded with url: /fundmetrology/eapi/vri?mit_number=14557-15&mi_number=3252&year=2024 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x71316fdbc980>, 'Connection to fgis.gost.ru timed out. (connect timeout=None)'))
2025-02-26 22:09:00,506 - app.routers.instruments - ERROR - Произошла ошибка при выполнении запроса к API 'АРШИН': HTTPSConnectionPool(host='fgis.gost.ru', port=443): Max retries exceeded with url: /fundmetrology/eapi/vri?mit_number=14557-15&mi_number=3252&year=2024 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x71316eb565d0>, 'Connection to fgis.gost.ru timed out. (connect timeout=None)'))
2025-02-26 22:09:04,602 - app.routers.instruments - ERROR - Произошла ошибка при выполнении запроса к API 'АРШИН': HTTPSConnectionPool(host='fgis.gost.ru', port=443): Max retries exceeded with url: /fundmetrology/eapi/vri?mit_number=14557-15&mi_number=3252&year=2025 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x71316eb56e90>, 'Connection to fgis.gost.ru timed out. (connect timeout=None)'))
2025-02-26 22:09:09,294 - app.routers.instruments - INFO - Начат поиск и добавление средства измерений для узла с ID=76. Параметры поиска: search=, mit_number=14557-15, mi_number=3252, year=2024
2025-02-26 22:09:09,294 - app.routers.instruments - INFO - Выполняется GET-запрос к API 'АРШИН' с параметрами: {'mit_number': '14557-15', 'mi_number': '3252', 'year': 2024}
2025-02-26 22:09:23,831 - app.routers.instruments - INFO - Начат поиск и добавление средства измерений для узла с ID=76. Параметры поиска: search=, mit_number=14557-15, mi_number=3252, year=2025
2025-02-26 22:09:23,832 - app.routers.instruments - INFO - Выполняется GET-запрос к API 'АРШИН' с параметрами: {'mit_number': '14557-15', 'mi_number': '3252', 'year': 2025}
2025-02-26 22:09:33,274 - app.routers.instruments - ERROR - Произошла ошибка при выполнении запроса к API 'АРШИН': HTTPSConnectionPool(host='fgis.gost.ru', port=443): Max retries exceeded with url: /fundmetrology/eapi/vri?mit_number=14557-15&mi_number=3252&year=2024 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x71316eb57110>, 'Connection to fgis.gost.ru timed out. (connect timeout=None)'))
2025-02-26 22:09:34,223 - app.routers.instruments - INFO - Начат поиск и добавление средства измерений для узла с ID=76. Параметры поиска: search=УДВН, mit_number=, mi_number=3252, year=2025
2025-02-26 22:09:34,223 - app.routers.instruments - INFO - Выполняется GET-запрос к API 'АРШИН' с параметрами: {'search': '*УДВН*', 'mi_number': '3252', 'year': 2025}
2025-02-26 22:09:39,354 - app.routers.instruments - INFO - Начат поиск и добавление средства измерений для узла с ID=76. Параметры поиска: search=УДВН, mit_number=, mi_number=3252, year=2024
2025-02-26 22:09:39,354 - app.routers.instruments - INFO - Выполняется GET-запрос к API 'АРШИН' с параметрами: {'search': '*УДВН*', 'mi_number': '3252', 'year': 2024}
2025-02-26 22:09:58,694 - app.routers.instruments - INFO - Начат поиск и добавление средства измерений для узла с ID=76. Параметры поиска: search=, mit_number=52866-13, mi_number=3252, year=2024
2025-02-26 22:09:58,694 - app.routers.instruments - INFO - Выполняется GET-запрос к API 'АРШИН' с параметрами: {'mit_number': '52866-13', 'mi_number': '3252', 'year': 2024}
2025-02-26 22:10:08,104 - app.routers.instruments - INFO - Начат поиск и добавление средства измерений для узла с ID=76. Параметры поиска: search=, mit_number=14557-15, mi_number=3252, year=2024
2025-02-26 22:10:08,105 - app.routers.instruments - INFO - Выполняется GET-запрос к API 'АРШИН' с параметрами: {'mit_number': '14557-15', 'mi_number': '3252', 'year': 2024}
2025-02-26 22:10:10,138 - app.routers.instruments - ERROR - Произошла ошибка при выполнении запроса к API 'АРШИН': HTTPSConnectionPool(host='fgis.gost.ru', port=443): Max retries exceeded with url: /fundmetrology/eapi/vri?search=%2A%D0%A3%D0%94%D0%92%D0%9D%2A&mit_number=14557-15&mi_number=3252&year=2024 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x71316eb57390>, 'Connection to fgis.gost.ru timed out. (connect timeout=None)'))
2025-02-26 22:10:11,826 - app.routers.instruments - INFO - Начат поиск и добавление средства измерений для узла с ID=76. Параметры поиска: search=, mit_number=14557-15, mi_number=3252, year=2024
2025-02-26 22:10:11,826 - app.routers.instruments - INFO - Выполняется GET-запрос к API 'АРШИН' с параметрами: {'mit_number': '14557-15', 'mi_number': '3252', 'year': 2024}
2025-02-26 22:10:18,331 - app.routers.instruments - ERROR - Произошла ошибка при выполнении запроса к API 'АРШИН': HTTPSConnectionPool(host='fgis.gost.ru', port=443): Max retries exceeded with url: /fundmetrology/eapi/vri?search=%2A%D0%A3%D0%94%D0%92%D0%9D%2A&mi_number=3252&year=2024 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x71316eb57610>, 'Connection to fgis.gost.ru timed out. (connect timeout=None)'))
2025-02-26 22:10:18,333 - app.routers.instruments - INFO - Начат поиск и добавление средства измерений для узла с ID=76. Параметры поиска: search=, mit_number=14557-15, mi_number=3252, year=2024
2025-02-26 22:10:18,333 - app.routers.instruments - INFO - Выполняется GET-запрос к API 'АРШИН' с параметрами: {'mit_number': '14557-15', 'mi_number': '3252', 'year': 2024}
2025-02-26 22:10:59,290 - app.routers.instruments - ERROR - Произошла ошибка при выполнении запроса к API 'АРШИН': HTTPSConnectionPool(host='fgis.gost.ru', port=443): Max retries exceeded with url: /fundmetrology/eapi/vri?search=%2A%D0%A3%D0%94%D0%92%D0%9D%2A&mi_number=3252&year=2024 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x71316eb57890>, 'Connection to fgis.gost.ru timed out. (connect timeout=None)'))
2025-02-26 22:11:23,866 - app.routers.instruments - ERROR - Произошла ошибка при выполнении запроса к API 'АРШИН': HTTPSConnectionPool(host='fgis.gost.ru', port=443): Max retries exceeded with url: /fundmetrology/eapi/vri?mit_number=14557-15&mi_number=3252&year=2024 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x71316eb57b10>, 'Connection to fgis.gost.ru timed out. (connect timeout=None)'))
2025-02-26 22:11:40,251 - app.routers.instruments - ERROR - Произошла ошибка при выполнении запроса к API 'АРШИН': HTTPSConnectionPool(host='fgis.gost.ru', port=443): Max retries exceeded with url: /fundmetrology/eapi/vri?mit_number=14557-15&mi_number=3252&year=2025 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x71316eb57d90>, 'Connection to fgis.gost.ru timed out. (connect timeout=None)'))
2025-02-26 22:11:48,443 - app.routers.instruments - ERROR - Произошла ошибка при выполнении запроса к API 'АРШИН': HTTPSConnectionPool(host='fgis.gost.ru', port=443): Max retries exceeded with url: /fundmetrology/eapi/vri?search=%2A%D0%A3%D0%94%D0%92%D0%9D%2A&mi_number=3252&year=2025 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x71316ec08050>, 'Connection to fgis.gost.ru timed out. (connect timeout=None)'))
2025-02-26 22:11:52,539 - app.routers.instruments - ERROR - Произошла ошибка при выполнении запроса к API 'АРШИН': HTTPSConnectionPool(host='fgis.gost.ru', port=443): Max retries exceeded with url: /fundmetrology/eapi/vri?search=%2A%D0%A3%D0%94%D0%92%D0%9D%2A&mi_number=3252&year=2024 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x71316eb57ed0>, 'Connection to fgis.gost.ru timed out. (connect timeout=None)'))
2025-02-26 22:12:13,018 - app.routers.instruments - ERROR - Произошла ошибка при выполнении запроса к API 'АРШИН': HTTPSConnectionPool(host='fgis.gost.ru', port=443): Max retries exceeded with url: /fundmetrology/eapi/vri?mit_number=52866-13&mi_number=3252&year=2024 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x71316eb55d10>, 'Connection to fgis.gost.ru timed out. (connect timeout=None)'))
2025-02-26 22:12:21,210 - app.routers.instruments - ERROR - Произошла ошибка при выполнении запроса к API 'АРШИН': HTTPSConnectionPool(host='fgis.gost.ru', port=443): Max retries exceeded with url: /fundmetrology/eapi/vri?mit_number=14557-15&mi_number=3252&year=2024 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x71316eb56ad0>, 'Connection to fgis.gost.ru timed out. (connect timeout=None)'))
2025-02-26 22:12:25,306 - app.routers.instruments - ERROR - Произошла ошибка при выполнении запроса к API 'АРШИН': HTTPSConnectionPool(host='fgis.gost.ru', port=443): Max retries exceeded with url: /fundmetrology/eapi/vri?mit_number=14557-15&mi_number=3252&year=2024 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x71316eb56c10>, 'Connection to fgis.gost.ru timed out. (connect timeout=None)'))
2025-02-26 22:12:33,498 - app.routers.instruments - ERROR - Произошла ошибка при выполнении запроса к API 'АРШИН': HTTPSConnectionPool(host='fgis.gost.ru', port=443): Max retries exceeded with url: /fundmetrology/eapi/vri?mit_number=14557-15&mi_number=3252&year=2024 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x71316eb55e50>, 'Connection to fgis.gost.ru timed out. (connect timeout=None)'))
